---
- name: Configure R {{ r_version }}
  become: yes
  args:
    executable: /bin/bash
  ansible.builtin.shell:
    cmd: > 
      cd "{{ r_root }}/R-{{ r_version }}/" && 
      ./configure 
      --prefix="{{ r_root }}/R-{{ r_version }}/" 
      --enable-R-shlib 
      --enable-R-profiling 
      --enable-memory-profiling 
      --with-blas 
      --with-lapack 
      --with-tcltk 

- name: Make R {{ r_version }}
  become: yes
  args:
    executable: /bin/bash
  ansible.builtin.shell: 
    cmd: >
      cd "{{ r_root }}/R-{{ r_version }}/" && 
      make

- name: Install R {{ r_version }}
  become: yes
  args:
    executable: /bin/bash
  ansible.builtin.shell: 
    cmd: >
      cd "{{ r_root }}/R-{{ r_version }}/" && 
      make install
