---
- name: Download Hadoop {{ hadoop_version }} to Hadoop directory
  ansible.builtin.get_url:
    url: "https://downloads.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_root }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    checksum: sha512:1f5762682cef3daff8b2379fe7e40efca107bb7e8dcaa4a513e3bc0c082067759dd05d493ec997433dde2c89ea63dbc93aee0bba60045f89d3ec2d3f687f58b3
