---
- name: stop hadoop cluster
  hosts: master
  user: bartok
  become: yes
  become_user: bartok
  tasks:
    - name: stop dfs
      ansible.builtin.command: stop-dfs.sh
    - name: stop mapred
      ansible.builtin.command: stop-mapred.sh
    - name: stop yarn
      ansible.builtin.command: stop-yarn.sh
      