---
- name: stop spark cluster
  hosts: master
  user: bartok
  become: yes
  become_user: bartok
  tasks:
    - name: stop master
      ansible.builtin.command: stop-master.sh
    - name: stop workers
      ansible.builtin.command: stop-workers.sh