---
- name: start spark cluster
  hosts: master
  user: bartok
  become: yes
  become_user: bartok
  tasks:
    - name: start master
      ansible.builtin.command: start-master.sh
    - name: start workers
      ansible.builtin.command: start-workers.sh
      