---
- name: upgrade apt
  hosts: all
  become: yes
  become_user: "{{ sudo_user }}"
  tasks:
    - name: upgrade (and update) apt
      apt:
        ansible.builtin.upgrade: yes
        update_cache: yes
        cache_valid_time: 86400