---
- name: Install {{ pip_pkg }}
  become: yes
  ansible.builtin.apt: 
    name: "{{ pip_pkg }}"
    state: present

- name: Install {{ figlet_pkg }}
  become: yes
  ansible.builtin.apt:
    name: "{{ figlet_pkg }}"
    state: present