---
- name: Copy {{ bash_aliases_filename }} file
  ansible.builtin.copy:
    src: "{{ bash_aliases_filename }}"
    dest: "{{ user_home }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Add sourcing of {{ bash_aliases_filename }} to .bashrc
  ansible.builtin.lineinfile:
      dest: "{{ bash_rc_file }}"
      line: "[[ -s {{ bash_aliases_file }} ]] && source {{ bash_aliases_file }}"
      owner: "{{ user }}"
      group: "{{ group }}"

- name: Copy {{ bash_commands_filename }} file to {{ user_home }}
  ansible.builtin.copy:
    src: "{{ bash_commands_filename }}"
    dest: "{{ user_home }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Copy {{ bash_commands_filename }} file to {{ etc_profile_d }}
  become: yes
  ansible.builtin.copy:
    src: "{{ bash_commands_filename }}"
    dest: "{{ etc_profile_d }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Rename {{ bash_commands_file }} in {{ etc_profile_d }} to execute first
  become: yes
  ansible.builtin.copy: 
    remote_src: yes
    src: "{{ etc_profile_d }}/{{ bash_commands_filename }}" 
    dest: "{{ etc_profile_d }}/aaa-commands.sh"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Add sourcing of {{ bash_commands_filename }} to {{ bash_rc_filename }}
  ansible.builtin.lineinfile:
    dest: "{{ bash_rc_file }}"
    insertbefore: BOF
    line: "[[ -s {{ bash_commands_file }} ]] && source {{ bash_commands_file }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Copy {{ bash_welcome_filename }} file
  ansible.builtin.copy:
    src: "{{ bash_welcome_filename }}"
    dest: "{{ user_home }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Add sourcing of {{ bash_welcome_filename }} to {{ bash_rc_filename }}
  ansible.builtin.lineinfile:
      dest: "{{ bash_rc_file }}"
      line: "[[ -s {{ bash_welcome_file }} ]] && source {{ bash_welcome_file }}"
      owner: "{{ user }}"
      group: "{{ group }}"
