---
- name: Copy file {{ hosts_file }} to {{ hosts_dir }}
  become: yes
  ansible.builtin.template:
    src: "{{ hosts_file }}"
    dest: "{{ hosts_dir }}"

- name: Copy {{ dhcpcd_file }} to {{ dhcpcd_dir }}
  become: yes
  ansible.builtin.template:
    src: "{{ dhcpcd_file }}"
    dest: "{{ dhcpcd_dir }}"

- name: Block WiFi interface
  become: yes
  ansible.builtin.shell:
    cmd: sudo rfkill block wifi