---
# - name: Git clone {{ pfetch_pkg }}
#   args:
#     executable: /bin/bash
#   ansible.builtin.shell:
#     cmd: "git clone {{ pfetch_url }} {{ user_download_dir }}/{{ pfetch_pkg }}"

- name: Copy {{ pfetch_pkg }} to remote host
  ansible.builtin.copy:
    src: ~/Downloads/{{ pfetch_pkg }}
    dest: "{{ user_download_dir }}"

- name: Install {{ pfetch_pkg }}
  become: yes
  args:
    executable: /bin/bash
  ansible.builtin.shell: 
    cmd: "sudo install {{ user_download_dir }}/{{ pfetch_pkg }}/{{ pfetch_pkg }} {{ user_install_dir }}"
